# Generated by Django 5.2.4 on 2026-05-10 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('camera_login', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_password', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_address', models.GenericIPAddressField(blank=True, null=True)),
                ('camera_port', models.IntegerField(blank=True, default=554, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('camera_path', models.CharField(default='/stream1', help_text='Остаток пути после IP и порта', max_length=255)),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
    ]
