# Generated by Django 5.2.4 on 2026-05-24 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='onvif_port',
            field=models.IntegerField(blank=True, default=80, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
