# Generated by Django 5.2.4 on 2026-05-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_camera_onvif_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Например: 2026-05-24_12-00-00.mp4', max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(help_text='Путь внутри контейнера Django для проверки физического наличия', max_length=500, unique=True, verbose_name='Полный путь к файлу')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Размер файла (в байтах)')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Время начала записи')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Длительность куска видео (выставляется на основе конфига MediaMTX)', verbose_name='Длительность (сек.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в базу')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Запись архива',
                'verbose_name_plural': 'Записи архива',
                'ordering': ['-start_time'],
            },
        ),
    ]
