# Generated by Django 5.2.4 on 2026-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_camerarecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_recording',
            field=models.BooleanField(default=False, verbose_name='Статус записи (Запущена/Остановлена)'),
        ),
    ]
